//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReniecSoap
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://endpoint.wsconsultadni.reniec.gob.pe/", ConfigurationName="ServiceReniecSoap.SRELServiceService")]
    public interface SRELServiceService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.wsconsultadni.reniec.gob.pe/SRELServiceService/consultarRequest", ReplyAction="http://endpoint.wsconsultadni.reniec.gob.pe/SRELServiceService/consultarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ServiceReniecSoap.resultadoConsulta> consultarAsync(ServiceReniecSoap.peticionConsulta arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.wsconsultadni.reniec.gob.pe/SRELServiceService/actualizarCredenci" +
            "alRequest", ReplyAction="http://endpoint.wsconsultadni.reniec.gob.pe/SRELServiceService/actualizarCredenci" +
            "alResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ServiceReniecSoap.resultadoActualizacionCredencial> actualizarCredencialAsync(ServiceReniecSoap.peticionActualizarCredencial arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.wsconsultadni.reniec.gob.pe/SRELServiceService/consultarCertifica" +
            "doRequest", ReplyAction="http://endpoint.wsconsultadni.reniec.gob.pe/SRELServiceService/consultarCertifica" +
            "doResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ServiceReniecSoap.resultadoConsulta> consultarCertificadoAsync(ServiceReniecSoap.peticionConsultaCertificado arg0);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.wsconsultadni.reniec.gob.pe/")]
    public partial class peticionConsulta
    {
        
        private string nuDniConsultaField;
        
        private string nuDniUsuarioField;
        
        private string nuRucUsuarioField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nuDniConsulta
        {
            get
            {
                return this.nuDniConsultaField;
            }
            set
            {
                this.nuDniConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nuDniUsuario
        {
            get
            {
                return this.nuDniUsuarioField;
            }
            set
            {
                this.nuDniUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nuRucUsuario
        {
            get
            {
                return this.nuRucUsuarioField;
            }
            set
            {
                this.nuRucUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.wsconsultadni.reniec.gob.pe/")]
    public partial class peticionConsultaCertificado
    {
        
        private string accessTokenField;
        
        private string nuDniConsultaField;
        
        private string nuRucUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accessToken
        {
            get
            {
                return this.accessTokenField;
            }
            set
            {
                this.accessTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nuDniConsulta
        {
            get
            {
                return this.nuDniConsultaField;
            }
            set
            {
                this.nuDniConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nuRucUsuario
        {
            get
            {
                return this.nuRucUsuarioField;
            }
            set
            {
                this.nuRucUsuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.wsconsultadni.reniec.gob.pe/")]
    public partial class resultadoActualizacionCredencial
    {
        
        private string coResultadoField;
        
        private string deResultadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string coResultado
        {
            get
            {
                return this.coResultadoField;
            }
            set
            {
                this.coResultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string deResultado
        {
            get
            {
                return this.deResultadoField;
            }
            set
            {
                this.deResultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.wsconsultadni.reniec.gob.pe/")]
    public partial class peticionActualizarCredencial
    {
        
        private string credencialAnteriorField;
        
        private string credencialNuevaField;
        
        private string nuDniField;
        
        private string nuRucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string credencialAnterior
        {
            get
            {
                return this.credencialAnteriorField;
            }
            set
            {
                this.credencialAnteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string credencialNueva
        {
            get
            {
                return this.credencialNuevaField;
            }
            set
            {
                this.credencialNuevaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nuDni
        {
            get
            {
                return this.nuDniField;
            }
            set
            {
                this.nuDniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nuRuc
        {
            get
            {
                return this.nuRucField;
            }
            set
            {
                this.nuRucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.wsconsultadni.reniec.gob.pe/")]
    public partial class datosPersona
    {
        
        private string dniField;
        
        private string prenombresField;
        
        private string primerApellidoField;
        
        private string apellidoCasadaField;
        
        private string segundoApellidoField;
        
        private string fechaNacimientoField;
        
        private string generoField;
        
        private string estadoCivilField;
        
        private string restriccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dni
        {
            get
            {
                return this.dniField;
            }
            set
            {
                this.dniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string prenombres
        {
            get
            {
                return this.prenombresField;
            }
            set
            {
                this.prenombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string primerApellido
        {
            get
            {
                return this.primerApellidoField;
            }
            set
            {
                this.primerApellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string apellidoCasada
        {
            get
            {
                return this.apellidoCasadaField;
            }
            set
            {
                this.apellidoCasadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string segundoApellido
        {
            get
            {
                return this.segundoApellidoField;
            }
            set
            {
                this.segundoApellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string genero
        {
            get
            {
                return this.generoField;
            }
            set
            {
                this.generoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string estadoCivil
        {
            get
            {
                return this.estadoCivilField;
            }
            set
            {
                this.estadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string restriccion
        {
            get
            {
                return this.restriccionField;
            }
            set
            {
                this.restriccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.wsconsultadni.reniec.gob.pe/")]
    public partial class resultadoConsulta
    {
        
        private string coResultadoField;
        
        private string deResultadoField;
        
        private datosPersona datosPersonaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string coResultado
        {
            get
            {
                return this.coResultadoField;
            }
            set
            {
                this.coResultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string deResultado
        {
            get
            {
                return this.deResultadoField;
            }
            set
            {
                this.deResultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public datosPersona datosPersona
        {
            get
            {
                return this.datosPersonaField;
            }
            set
            {
                this.datosPersonaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SRELServiceServiceChannel : ServiceReniecSoap.SRELServiceService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SRELServiceServiceClient : System.ServiceModel.ClientBase<ServiceReniecSoap.SRELServiceService>, ServiceReniecSoap.SRELServiceService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SRELServiceServiceClient() : 
                base(SRELServiceServiceClient.GetDefaultBinding(), SRELServiceServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SRELServiceServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SRELServiceServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SRELServiceServiceClient.GetBindingForEndpoint(endpointConfiguration), SRELServiceServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SRELServiceServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SRELServiceServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SRELServiceServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SRELServiceServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SRELServiceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReniecSoap.resultadoConsulta> consultarAsync(ServiceReniecSoap.peticionConsulta arg0)
        {
            return base.Channel.consultarAsync(arg0);
        }
        
        public System.Threading.Tasks.Task<ServiceReniecSoap.resultadoActualizacionCredencial> actualizarCredencialAsync(ServiceReniecSoap.peticionActualizarCredencial arg0)
        {
            return base.Channel.actualizarCredencialAsync(arg0);
        }
        
        public System.Threading.Tasks.Task<ServiceReniecSoap.resultadoConsulta> consultarCertificadoAsync(ServiceReniecSoap.peticionConsultaCertificado arg0)
        {
            return base.Channel.consultarCertificadoAsync(arg0);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SRELServiceServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SRELServiceServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://jfloresh.reniec.gob.pe/wsconsultadni/ConsultaDniService");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SRELServiceServiceClient.GetBindingForEndpoint(EndpointConfiguration.SRELServiceServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SRELServiceServiceClient.GetEndpointAddress(EndpointConfiguration.SRELServiceServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            SRELServiceServicePort,
        }
    }
}
